### ISSUE TITLE
mint-ui:日期时间插件设置为只显示年月

### ISSUE THREAD

**Issue by openks** [openks/learn-vue#23]

**Comment by openks** [comment]
方案一： 隐藏掉日选择器     
方案二： 使用picker重新绘制一个只有年月的picker

```html
  <mt-datetime-picker
    class="yearMonth"
    ref="picker"
    type="date"
    year-format="{value} 年"
    month-format="{value} 月"
    date-format="{value} 日"
    v-model="time"
    @confirm="handleConfirm"
    >
  </mt-datetime-picker>
```
```scss
.yearMonth{
  .picker-items {
    .picker-slot-center:nth-child(3) {
      flex:0 0 0%!important;
      background-color:red;
    }
  }
}
```
